export default {
  "+ Add Horizontal Giude": "+ Adicionar Guia Horizontal",
  "+ Add Vertical Giude": "+ Adicionar Guia Vertical",
  "2D View": "Vista 2D",
  "3D First Person": "3D Primeira Pessoa",
  "3D View": "Vista 3D",
  "altitude": "altitude",
  "Altitude": "Altitude",
  "Areas": "Areas",
  "Call Planfinder": "Call Planfinder",
  "Cancel": "Cancelar",
  "Catalog": "Catalogo",
  "Chain selected Elements to Group": "Encadear Elementos selecionados para Agrupar",
  "Circular": "Circular",
  "color": "cor",
  "Configure layer": "Configurar layer",
  "Configure project": "Configurar projeto",
  "Confirm": "Confirmar",
  "Copy": "Copiar",
  "Delete group and all Elements": "Apagar grupo e todos os Elementos",
  "Delete layer": "Apagar layer",
  "Delete": "Apagar",
  "Elements on layer {0}": "Elementos da layer {0}",
  "Elements": "Elementos",
  "Get Screenshot": "Get Screenshot",
  "Group [{0}]": "Group [{0}]",
  "Group's Barycenter": "Baricentro do Grupo",
  "Group's Elements": "Elementos do Grupo",
  "Groups": "Grupps",
  "Guides": "Guias",
  "height": "altura",
  "Holes": "Buracos",
  "Horizontal": "Horizontal",
  "Items": "Items",
  "Last Selected":" Último Selecionado",
  "Layer config": "Configuração de layer",
  "Layer": "Layer",
  "Layers": "Layers",
  "Length": "Comprimento",
  "Lines": "Linhas",
  "Load project": "Importar projeto",
  "Mouse X Coordinate": "Coordenadas Rato X",
  "Mouse Y Coordinate": "Coordenadas Rato Y Coordinate",
  "Name": "Nome",
  "New Empty Group": "Novo Grupo Vazio",
  "New Group from selected": "New Group from selected",
  "New layer": "Nova layer",
  "New project": "Novo projeto",
  "opacity": "opacidade",
  "Open catalog": "Abrir catalogo",
  "order": "ordem",
  "Pan": "Pan",
  "Paste": "Colar",
  "Project config": "Configuração de projeto",
  "Properties: [{0}] {1}": "Propriedades: [{0}] {1}",
  "Prototype": "Prototipo",
  "Reset": "Reset",
  "Rotation" : "Rotação",
  "Save project": "Guardar projeto",
  "Save": "Guardar",
  "Scene Zoom Level": "Nível de Zoom da Cena",
  "Search Element": "Procurar Elemento",
  "Snap to Grid": "Ajustar à Grelha",
  "Snap to Guide": "Ajustar ao Guia",
  "Snap to Line": "Ajustar à Linha",
  "Snap to Point": "Ajustar ao Ponto",
  "Snap to Segment": "Ajustar ao  Segmento",
  "texture": "textura",
  "thickness": "grossura",
  "Toggle Group Visibility": "Alternar Visibilidade do Grupo",
  "Un-chain all Group\'s Elements and remove Group": "Desencadiar todos os Elementos do Grupo e remover o Grupo",
  "Un-chain Element from Group": "Desencadiar todos os Elementos do Grup",
  "Undo (CTRL-Z)": "Desfazer (CTRL-Z)",
  "Redo (CTRL-Y)": "Refazer (CTRL-Y)",
  "Unselect": "Desmarcar",
  "Vertical": "Vertical",
  "width": "largura",
  "Would you want to start a new Project?": "Deseja iniciar um novo projeto?",
  "Zoom in": "Zoom in",
  "Zoom out": "Zoom out"
};
